# render.yaml
services:
  - type: web
    name: wefit
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: standard
    healthCheckPath: /health  # Ensure you have a health endpoint
    envVars:
      - key: NODE_ENV
        value: production